backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    format: yaml-frontmatter
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        summary: "{{fields.quote}} - {{fields.author.name}}"
        fields:
          - label: Quote
            name: quote
            widget: string
            default: "Everything is awesome!"
          - label: Author
            name: author
            widget: object
            fields:
              - { label: Name, name: name, widget: string, default: "Emmet" }
              - {
                  label: Avatar,
                  name: avatar,
                  widget: image,
                  default: "/img/tlock.png",
                }
      - label: "Body"
        name: "body"
        widget: "markdown"
